---
title: "Latihan2_123190036"
author: "Sabrina Dian Isawri"
date: "9/23/2021"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

# Nomer 1
```
str(murders)
```
### 'data.frame':	51 obs. of  5 variables:
### $ state     : chr  "Alabama" "Alaska" "Arizona" "Arkansas" ...
### $ abb       : chr  "AL" "AK" "AZ" "AR" ...
### $ region    : Factor w/ 4 levels "Northeast","South",..: 2 4 4 2 4 4 1 2   2 2 ...
### $ population: num  4779736 710231 6392017 2915918 37253956 ...
### $ total     : num  135 19 232 93 1257 ...
 
### Pilihan yang benaradalah C. Data berisi nama Negara bagian, singkatan dari beberapa negara bagian, wilayah negara bagian, dan pupolasi negara bagian serta jumlah total pembunuhan pada tahun 2010. sesuai dengan hasil tampilan setelah menulis str(murders) di consonel dan menekan enter maka hasil yang muncul sama seperti apa yang dikatakan oleh pilihan C.


# Nomer 2
```
> names(murders)
> [1] "state"      "abb"        "region"     "population" "total"
```
### nama kolom yang digunakan adalah state, abb, region, population, total.

# nomer 3
```
> a  = murders$abb
> class(a)
[1] "character"
```
### abb tersimpan di variabel a dan bertipe data char.

# nomer 4 
```
> b = murders[[2]]
> class(b)
[1] "character"
```
### Mengestrak singkatan negara dan menyimpannya pada variabel b.
```
> a == b 
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[46] TRUE TRUE TRUE TRUE TRUE TRUE
```
### Hasil perbandingan semuanya TRUE maka kedua variabel memiliki data yang sama 

# Nomor 5 
### Menentukan jumlah region yang dimiliki oleh dataset 
```
> length(levels(murders$region))
[1] 4
```

# Nomer 6 
### Menampilkan table yang berisi jumlah state pada tiap region 
```
> table(murders$region)

    Northeast         South North Central          West 
            9            17            12            13 
```

